appname = diplomas_crud
httpport = ${DIPLOMAS_CRUD_HTTP_PORT||8080}
runmode = ${DIPLOMAS_CRUD_RUNMODE||prod}
autorender = false
copyrequestbody = true
EnableDocs = true
parameterStore = ${PARAMETER_STORE}

PGuser = ${DIPLOMAS_CRUD_PGUSER||postgres}
PGpass = ${DIPLOMAS_CRUD_PGPASS||postgres}
PGhost = ${DIPLOMAS_CRUD_PGHOST||127.0.0.1}
PGport = ${DIPLOMAS_CRUD_PGPORT||5432}
PGdb = ${DIPLOMAS_CRUD_PGDB||udistrital_academica}
PGschema = ${DIPLOMAS_CRUD_PGSCHEMA||diplomas}


