appname = diplomas_crud
httpport = ${DIPLOMAS_CRUD_HTTP_PORT}
runmode = ${DIPLOMAS_CRUD_RUNMODE}
autorender = false
copyrequestbody = true
EnableDocs = true
parameterStore = ${PARAMETER_STORE}

PGuser = ${DIPLOMAS_CRUD_PGUSER}
PGpass = ${DIPLOMAS_CRUD_PGPASS}
PGhost = ${DIPLOMAS_CRUD_PGHOST}
PGport = ${DIPLOMAS_CRUD_PGPORT}
PGdb = ${DIPLOMAS_CRUD_PGDB}
PGschema = ${DIPLOMAS_CRUD_PGSCHEMA}

