package routers

import (
	beego "github.com/beego/beego/v2/server/web"

	"github.com/udistrital/diplomas_crud/controllers"
)

func init() {
	api := beego.NewNamespace("/v1",
		beego.NSNamespace("/documento_digital",
			beego.NSRouter("/", &controllers.DocumentoDigitalController{}, "get:GetAll;post:Post"),
			beego.NSRouter("/:id", &controllers.DocumentoDigitalController{}, "get:GetOne;put:Put;delete:Delete"),
			beego.NSRouter("/:id/estado", &controllers.DocumentoDigitalController{}, "post:CambiarEstado"),
			beego.NSRouter("/:id/uuid", &controllers.DocumentoDigitalController{}, "put:ActualizarUUID"),
			beego.NSRouter("/:id/firma", &controllers.DocumentoDigitalController{}, "post:RegistrarFirma"),
			beego.NSRouter("/:id/diploma", &controllers.DocumentoDigitalController{}, "post:CrearDiploma"),
		),
		beego.NSNamespace("/diploma_digital",
			beego.NSRouter("/", &controllers.DiplomaDigitalController{}, "get:GetAll;post:Post"),
			beego.NSRouter("/:id", &controllers.DiplomaDigitalController{}, "get:GetOne;put:Put;delete:Delete"),
		),
		beego.NSNamespace("/firma_firmante",
			beego.NSRouter("/", &controllers.FirmaFirmanteController{}, "get:GetAll;post:Post"),
			beego.NSRouter("/:id", &controllers.FirmaFirmanteController{}, "get:GetOne;put:Put;delete:Delete"),
		),
		beego.NSNamespace("/firma_documento",
			beego.NSRouter("/", &controllers.FirmaDocumentoController{}, "get:GetAll;post:Post"),
			beego.NSRouter("/:id", &controllers.FirmaDocumentoController{}, "get:GetOne;put:Put;delete:Delete"),
		),
		beego.NSNamespace("/parametrizacion_registro_facultad",
			beego.NSRouter("/", &controllers.ParametrizacionRegistroFacultadController{}, "get:GetAll;post:Post"),
			beego.NSRouter("/:id", &controllers.ParametrizacionRegistroFacultadController{}, "get:GetOne;put:Put;delete:Delete"),
		),
		beego.NSNamespace("/libro_registro",
			beego.NSRouter("/", &controllers.LibroRegistroController{}, "get:GetAll;post:Post"),
			beego.NSRouter("/:id", &controllers.LibroRegistroController{}, "get:GetOne;put:Put;delete:Delete"),
		),
		beego.NSNamespace("/folio_registro",
			beego.NSRouter("/", &controllers.FolioRegistroController{}, "get:GetAll;post:Post"),
			beego.NSRouter("/:id", &controllers.FolioRegistroController{}, "get:GetOne;put:Put;delete:Delete"),
		),
		beego.NSNamespace("/control_registro_facultad",
			beego.NSRouter("/", &controllers.ControlRegistroFacultadController{}, "get:GetAll;post:Post"),
			beego.NSRouter("/:id", &controllers.ControlRegistroFacultadController{}, "get:GetOne;put:Put;delete:Delete"),
		),
		beego.NSNamespace("/registro_grado",
			beego.NSRouter("/", &controllers.RegistroGradoController{}, "get:GetAll;post:Post"),
			beego.NSRouter("/:id", &controllers.RegistroGradoController{}, "get:GetOne;put:Put;delete:Delete"),
		),
		beego.NSNamespace("/ceremonia_grado",
			beego.NSRouter("/", &controllers.CeremoniaGradoController{}, "get:GetAll;post:Post"),
			beego.NSRouter("/:id", &controllers.CeremoniaGradoController{}, "get:GetOne;put:Put;delete:Delete"),
		),
		beego.NSNamespace("/ceremonia_facultad_programa",
			beego.NSRouter("/", &controllers.CeremoniaFacultadProgramaController{}, "get:GetAll;post:Post"),
			beego.NSRouter("/:id", &controllers.CeremoniaFacultadProgramaController{}, "get:GetOne;put:Put;delete:Delete"),
		),
		beego.NSNamespace("/ceremonia_estudiante",
			beego.NSRouter("/", &controllers.CeremoniaEstudianteController{}, "get:GetAll;post:Post"),
			beego.NSRouter("/:id", &controllers.CeremoniaEstudianteController{}, "get:GetOne;put:Put;delete:Delete"),
		),
		beego.NSNamespace("/historico_estado_documento",
			beego.NSRouter("/", &controllers.HistoricoEstadoDocumentoController{}, "get:GetAll;post:Post"),
			beego.NSRouter("/:id", &controllers.HistoricoEstadoDocumentoController{}, "get:GetOne;put:Put;delete:Delete"),
		),
	)

	beego.AddNamespace(api)
}
